-- Reference data every other table hangs off: customers, products, warehouses.
-- UUID primary keys are generated by Hibernate, not the database, so no
-- pgcrypto/uuid-ossp extension is required.

CREATE TABLE customers (
    id                    UUID PRIMARY KEY,
    odoo_partner_id       BIGINT UNIQUE,
    name                  VARCHAR(255)   NOT NULL,
    segment               VARCHAR(32)    NOT NULL,
    tier                  VARCHAR(32),
    region                VARCHAR(255),
    credit_limit          NUMERIC(18, 2),
    outstanding_balance   NUMERIC(18, 2),
    payment_terms_days    INTEGER,
    risk_score            INTEGER,
    on_time_payment_rate  NUMERIC(5, 2),
    active                BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ    NOT NULL DEFAULT NOW(),

    CONSTRAINT customers_segment_valid
        CHECK (segment IN ('ENTERPRISE', 'MID_MARKET', 'SMB', 'PARTNER')),
    CONSTRAINT customers_risk_score_range
        CHECK (risk_score IS NULL OR risk_score BETWEEN 0 AND 100)
);

CREATE INDEX idx_customers_segment ON customers (segment) WHERE active;

CREATE TABLE products (
    id               UUID PRIMARY KEY,
    odoo_product_id  BIGINT UNIQUE,
    sku              VARCHAR(64)    NOT NULL UNIQUE,
    name             VARCHAR(255)   NOT NULL,
    category         VARCHAR(64),
    list_price       NUMERIC(18, 2) NOT NULL,
    standard_cost    NUMERIC(18, 2) NOT NULL,
    floor_price      NUMERIC(18, 2),
    uom              VARCHAR(16)    NOT NULL DEFAULT 'UNIT',
    stock_on_hand    INTEGER        NOT NULL DEFAULT 0,
    lead_time_days   INTEGER        NOT NULL DEFAULT 0,
    active           BOOLEAN        NOT NULL DEFAULT TRUE,

    CONSTRAINT products_prices_non_negative
        CHECK (list_price >= 0 AND standard_cost >= 0)
);

CREATE INDEX idx_products_category ON products (category) WHERE active;

CREATE TABLE warehouses (
    id                 UUID PRIMARY KEY,
    odoo_warehouse_id  BIGINT UNIQUE,
    code               VARCHAR(16)  NOT NULL UNIQUE,
    name               VARCHAR(255) NOT NULL,
    region             VARCHAR(255),
    dispatch_days      INTEGER      NOT NULL DEFAULT 1,
    active             BOOLEAN      NOT NULL DEFAULT TRUE
);
