-- Adapted from feature/dbinit's V9__enterprise_hardening.sql. That branch
-- rewrote the schema from scratch under different table/column names
-- (users/tiers/customers/deals with owner_id, net_amount, approval_status as
-- a column, etc.) — incompatible with the JPA entities actually running on
-- this schema, so it could not be merged as written. The underlying hardening
-- ideas were sound; this re-targets the genuinely portable ones at the real,
-- running schema instead.
--
-- This migration was originally landed as V13__hardening_from_dbinit.sql
-- (PR #4, commit 44f21cf) but was silently dropped from dev during a later
-- migration renumbering pass (PR #7) that reused V13 for approval-snapshots
-- work. Restored at the next free version during dev consolidation, then
-- fully absorbed into the MySQL port's V13 (which now carries the triggers
-- and email-format constraint directly, and needs no separate FK-index
-- section — see V13's header). This file is intentionally a no-op, kept
-- only so the migration version number isn't reused or skipped.
